// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Label struct {
	Name  string `json:"name"`
	Image string `json:"image"`
}

type Order struct {
	ID        string    `json:"id"`
	Amount    float64   `json:"amount"`
	Status    int32     `json:"status"`
	UserID    string    `json:"userId"`
	CreatedAt time.Time `json:"createdAt"`
}

type OrderDetail struct {
	OrderID   string `json:"orderId"`
	ProductID string `json:"productId"`
	Quantity  int32  `json:"quantity"`
}

type Product struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	Image       string       `json:"image"`
	Description string       `json:"description"`
	Price       float64      `json:"price"`
	LabelName   string       `json:"labelName"`
	CreatedAt   sql.NullTime `json:"createdAt"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Address  string `json:"address"`
}
