// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Order struct {
	ID        string
	Amount    sql.NullFloat64
	Status    sql.NullInt32
	UserID    sql.NullString
	CreatedAt sql.NullTime
}

type OrderDetail struct {
	OrderID   sql.NullString
	ProductID sql.NullString
	Quantity  sql.NullInt32
}

type Product struct {
	ID          string
	Name        sql.NullString
	Image       sql.NullString
	Description sql.NullString
	Price       sql.NullFloat64
	CreatedAt   sql.NullTime
}

type User struct {
	ID       string
	Username sql.NullString
	Password sql.NullString
	Email    sql.NullString
	Phone    sql.NullString
	Address  sql.NullString
}
